linters:
  EmptyLineBetweenBlocks:
    enabled: false
  Comment:
    enabled: false
  PropertySortOrder:
    enabled: false
  NameFormat:
    convention: 'BEM' # hyphenated_lowercase or 'BEM', or a regex pattern
  SelectorFormat:
    convention: 'BEM' # hyphenated_lowercase or 'BEM', or 'snake_case', or 'camel_case', or a regex pattern
  Indentation:
    enabled: false